# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_dump_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='passengers_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='passengers_off',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reading',
            name='passengers_on',
            field=models.FloatField(),
        ),
    ]
